### ISSUE TITLE
小项目使用vw实现移动端适配 

### ISSUE THREAD

**Issue by liangfengbo** [liangfengbo/frontend-develop#4]
一、前端有提到如何在Vue项目中使用vw实现移动端适配 [跳转链接](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)

二、如果不是vue 的项目，一些简单的小项目，也可以直接自定义，需要的话，直接粘贴下面的css：

```css

html, body {
  font-size: 16px;
}

div {
  margin: 0;
  padding: 0;
}

@media screen and (min-width: 375px) {
  html {
    /* iPhone6的375px尺寸作为16px基准，414px正好18px大小, 600 20px */
    font-size: calc(100% + 2 * (100vw - 375px) / 39);
    font-size: calc(16px + 2 * (100vw - 375px) / 39);
  }
}

@media screen and (min-width: 414px) {
  html {
    /* 414px-1000px每100像素宽字体增加1px(18px-22px) */
    font-size: calc(112.5% + 4 * (100vw - 414px) / 586);
    font-size: calc(18px + 4 * (100vw - 414px) / 586);
  }
}

@media screen and (min-width: 600px) {
  html {
    /* 600px-1000px每100像素宽字体增加1px(20px-24px) */
    font-size: calc(125% + 4 * (100vw - 600px) / 400);
    font-size: calc(20px + 4 * (100vw - 600px) / 400);
  }
}

@media screen and (min-width: 1000px) {
  html {
    /* 1000px往后是每100像素0.5px增加 */
    font-size: calc(137.5% + 6 * (100vw - 1000px) / 1000);
    font-size: calc(22px + 6 * (100vw - 1000px) / 1000);
  }
}

```
